ABBREVIATIONS = {
    '\'not in my backyard\'-houding': 'nimby',
    '\'t is te zeggen': 't.t.z.',
    'escape': 'esc',
    'gemeentewerken': 'GW',
    'gevechtsvliegtuig van mikojan en goerevitsj': 'MiG',
    'fear of missing out': 'fomo',
    'joy of missing out': 'jomo',
    'ministerie van algemene zaken': 'AZ',
    'ministerie van binnenlandse zaken': 'BiZa',
    'ministerie van binnenlandse zaken en koninkrijksrelaties': 'BZK',
    'ministerie van buitenlandse zaken': 'BZ',
    'ministerie van economische zaken en klimaat': 'EZK',
    'ministerie van financiën': 'Fin.',
    'ministerie van infrastructuur en waterstaat': 'IenW',
    'ministerie van justitie en veiligheid': 'JenV',
    'ministerie van landbouw, natuur en voedselkwaliteit': 'LNV',
    'ministerie van onderwijs en wetenschappen': 'O en W',
    'ministerie van onderwijs, cultuur en wetenschap': 'OCW',
    'ministerie van sociale zaken en werkgelegenheid': 'SZW',
    'ministerie van verkeer en waterstaat': 'VenW',
    'ministerie van volksgezondheid, welzijn en sport': 'VWS',
    'ministerie van volkshuisvesting, ruimtelijke ordening en milieubeheer': 'VROM',
    'ministerie van welzijn, volksgezondheid en cultuur': 'WVC',
    'train à grande vitesse': 'TGV',
    'nieuwe stijl': 'n.s.',
    'oude stijl': 'o.s.',
    'automatische dubbele overwegbomen': 'adob',
    '10 oktober 2010': '10-10-10',
    '2 paardenkracht': '2pk',
    '3-methylmethcathinon': '3-MMC',
    '4-methylmethcathinon': '4-MMC',
    'a.v. roe and company': 'Avro',
    'aan de hand van': 'a.d.h.v.',
    'aan de': 'a.d.',
    'aan het woord': 'a.h.w.',
    'aanbevolen dagelijkse hoeveelheid': 'adh',
    'aangetekend': 'aanget.',
    'aanmeldcentrum': 'ac',
    'aanstaand': 'a.s.',
    'aantrekkelijk': 'aantr.',
    'aanvullend openbaar vervoer': 'aov',
    'aanvullend secundair beroepsonderwijs': 'asbo',
    'aanvullende pensioenrekening': 'APR',
    'aardappelen, groente, fruit': 'agf',
    'aardappelen, groente, vlees': 'agv',
    'aardappelen, vlees, groente': 'avg',
    'ablatief': 'abl.',
    'ablativus': 'abl.',
    'academie': 'acad.',
    'academisch ziekenhuis': 'az',
    'academische bacheloropleiding': 'aba',
    'accusatief': 'acc.',
    'accusativus': 'acc.',
    'acetylsalicylzuur, paracetamol, cafeïne': 'apc',
    'acquired immune deficiency syndrome': 'aids',
    'actief': 'act.',
    'acute flaccid myelitis': 'AFM',
    'ad hanc vocem': 'a.h.v.',
    'ad interim': 'a.i.',
    'ad libitum': 'ad lib.',
    'adjectief': 'adj.',
    'adjectivum': 'adj.',
    'administratie van fiscale zaken': 'AFZ',
    'afbeelding': 'afb.',
    'afdeling': 'afd.',
    'afgebroken': 'afg.',
    'afgelast': 'afg.',
    'afhankelijk': 'afh.',
    'afkorting': 'afk.',
    'afleiding': 'afl.',
    'aflevering': 'afl.',
    'aflossing': 'afl.',
    'afzender': 'afz.',
    'afzonderlijk': 'afz.',
    'agent van de staats sicherheitsdienst': 'stasi',
    'alcohol': 'alc.',
    'algemeen': 'alg.',
    'algemeen belgisch vakverbond': 'ABVV',
    'algemeen beschaafd nederlands': 'ABN',
    'algemeen bestuur': 'ab',
    'algemeen bestuur voor ontwikkelingssamenwerking': 'ABOS',
    'algemeen burgerlijk pensioenfonds': 'ABP',
    'algemeen christelijk middenstandsverbond': 'ACMV',
    'algemeen christelijk vakverbond': 'ACV',
    'algemeen christelijk verbond van werkgevers': 'ACVW',
    'algemeen christelijk werkliedenverbond': 'ACW',
    'algemeen nederlands persbureau': 'ANP',
    'algemeen nederlands': 'AN',
    'algemeen nut beogende instelling': 'anbi',
    'algemeen ouderenverbond': 'AOV',
    'algemeen plan van aanleg': 'apa',
    'algemeen secundair onderwijs': 'aso',
    'algemeen verbond bouwbedrijven': 'AVBB',
    'algemeen voortgezet onderwijs': 'avo',
    'algemeen ziekenhuis': 'az',
    'algemeen zuid-nederlands': 'AZN',
    'algemene arbeidsongeschiktheidswet': 'AAW',
    'algemene bestedingsbelasting': 'abb',
    'algemene bond uitzendverenigingen': 'ABU',
    'algemene bond van onderwijzend personeel': 'ABOP',
    'algemene centrale der liberale vakbonden van belgië': 'ACLVB',
    'algemene centrale der openbare diensten': 'ACOD',
    'algemene dagelijkse levensverrichtingen': 'adl',
    'algemene dienst inlichting en veiligheid': 'ADIV',
    'algemene handelsvoorwaarden': 'ahv',
    'algemene inlichtingen- en veiligheidsdienst': 'AIVD',
    'algemene kinderbijslagwet': 'AKW',
    'algemene ledenvergadering': 'alv',
    'algemene maatregel van bestuur': 'AMvB',
    'algemene middelbare school': 'AMS',
    'algemene nabestaandenwet': 'Anw',
    'algemene natuurwetenschappen': 'anw',
    'algemene nederlandsche wielrijdersbond': 'ANWB',
    'algemene ondernemersvaardigheden': 'aov',
    'algemene oudedagsvoorziening (suriname)': 'AOV',
    'algemene ouderdomsverzekering (antillen)': 'AOV',
    'algemene ouderdomswet': 'AOW',
    'algemene periodieke keuring': 'apk',
    'algemene plaatselijke verordening': 'apv',
    'algemene programmaraad': 'APR',
    'algemene raad van het katholiek onderwijs': 'ARKO',
    'algemene vereniging radio omroep': 'AVRO',
    'algemene vereniging van beroepsjournalisten in belgië': 'AVBB',
    'algemene verordening gegevensbescherming': 'AVG',
    'algemene verzekering bijzondere ziektekosten': 'AVBZ',
    'algemene weduwen- en wezenwet': 'AWW',
    'algemene wet bijzondere ziektekosten': 'AWBZ',
    'alleenstaande minderjarige asielzoeker': 'ama',
    'alleenstaande minderjarige vreemdeling': 'amv',
    'alles voor vlaanderen, vlaanderen voor kristus': 'AVV/VVK',
    'allterrainbike': 'ATB',
    'alpha-linolenic acid': 'ALA',
    'als gevolg van': 'a.g.v.',
    'als het ware': 'a.h.w.',
    'alsjeblieft': 'ajb.',
    'also known as': 'aka',
    'alstublieft': 'a.u.b.',
    'alternatieve combinatie': 'AC',
    'ambtenaar openbare veiligheid': 'AOV',
    'amsterdam exchanges index': 'AEX',
    'amyotrofische laterale sclerose': 'ALS',
    'analog digital digital': 'ADD',
    'anno domini': 'A.D.',
    'anonieme alcoholisten': 'AA',
    'ante meridiem': 'a.m.',
    'antidiuretisch hormoon': 'ADH',
    'antilock braking system': 'ABS',
    'anton de kom universiteit van suriname': 'Adekus',
    'apparaat': 'app.',
    'appartement': 'app.',
    'appellant': 'app.',
    'appellante': 'app.',
    'appellation contrôlée': 'A.C.',
    'appellation d\'origine contrôlée': 'A.O.C.',
    'appendix': 'app.',
    'application programming interface': 'API',
    'april': 'apr',
    'arab league educational, cultural and scientific organization': 'ALECSO',
    'arbeidersjeugdcentrale': 'AJC',
    'arbeidsduurverkorting': 'adv',
    'arbeidsmarktgekwalificeerd assistent': 'aka',
    'arbeidsongeschikheidsverzekering': 'aov',
    'arbeidsplaatsenovereenkomst': 'apo',
    'arbeidstijdverkorting': 'atv',
    'archief en museum voor het vlaams leven te brussel': 'AMVB',
    'armée patriotique rwandaise': 'APR',
    'artificial intelligence': 'AI',
    'artificiële intelligentie': 'AI',
    'artikel': 'art.',
    'arts in opleiding tot specialist': 'aios',
    'arts niet in opleiding tot specialist': 'anios',
    'arts voor verstandelijk gehandicapten': 'avg',
    'arts-geneeskundige in opleiding': 'agio',
    'arubaanse volkspartij': 'AVP',
    'as soon as possible': 'asap',
    'asielzoekerscentrum': 'azc',
    'assistent in opleiding': 'aio',
    'assistent-geneeskundige niet in opleiding': 'agnio',
    'assisterend academisch personeel': 'AAP',
    'associatie van surinaamse fabrikanten': 'ASFA',
    'asymmetric digital subscriber line': 'ADSL',
    'athlitiki enosis konstantinoupoleos': 'AEK',
    'atlantische partnerschapsraad': 'APR',
    'attention deficit disorder': 'ADD',
    'attention deficit hyperactivity disorder': 'ADHD',
    'audiovisueel': 'av',
    'augmented reality': 'AR',
    'augustus': 'aug',
    'auto-immuunhepatitis': 'AIH',
    'automatic number plate recognition': 'ANPR',
    'automatische externe defibrillator': 'aed',
    'automatische prijscompensatie': 'apc',
    'autonome raad voor het gemeenschapsonderwijs': 'ARGO',
    'autoriteit financiële markten': 'AFM',
    'avondklok': 'avklo',
    'azië en latijns-amerika': 'ALA',
    'bacardi cola': 'baco',
    'baccalaureus': 'bc.',
    'bachelor': 'ba',
    'bachelor (titel)': 'B',
    'bachelor of arts': 'BA',
    'bachelor of science': 'BSc',
    'bachelor-master': 'bama',
    'bachelor-na-bacheloropleiding': 'banaba',
    'bachelor-na-masteropleiding': 'banama',
    'bank identifier code': 'BIC',
    'banksysteem geleverd door de society for worldwide interbank financial telecommunication': 'Swift',
    'barbecue': 'bbq',
    'basic input output system': 'BIOS',
    'basisberoepsgerichte leerweg': 'bbl',
    'basisonderwijs': 'bo',
    'basisverzekering ziektekosten': 'bvz',
    'be right back': 'brb',
    'beats per minute': 'bpm',
    'bed and breakfast': 'B&B',
    'bed, bad, brood': 'bbb',
    'bedrijfshulpverlening': 'bhv',
    'beelden per seconde': 'bps',
    'before exceptional items and amortization': 'beia',
    'begane grond': 'b.g.',
    'bekende vlaming': 'BV',
    'belasting op bedrijfsomzetten': 'bbo',
    'belasting over de toegevoegde waarde': 'btw',
    'belastingregeling voor het koninkrijk': 'BRK',
    'belgisch': 'Belg.',
    'belgisch kampioenschap': 'BK',
    'belgisch olympisch en interfederaal comité': 'BOIC',
    'belgisch warmbloedpaard': 'BWP',
    'belgische frank': 'Bfr.',
    'belgische mij. voor int. investeringen': 'BMI',
    'belgische radio- en televisieomroep': 'BRT',
    'belgische radio- en televisieomroep nederlandstalige uitzendingen': 'BRTN',
    'belgischer rundfunk': 'BRF',
    'belgië': 'Belg.',
    'belgië, nederland en luxemburg': 'Benelux',
    'bepaald': 'bep.',
    'beroeps voor bepaalde tijd': 'bbt',
    'beroepsbegeleidende leerweg': 'bbl',
    'beroepsonderwijs en volwasseneducatie': 'bve',
    'beroepssecundair onderwijs': 'bso',
    'beroepsvereniging van nederlandse ontwerpers': 'BNO',
    'bescherming bevolking': 'BB',
    'beschikking geen loonheffingen': 'BGL',
    'besloten vennootschap': 'bv',
    'besloten vennootschap met beperkte aansprakelijkheid': 'bvba',
    'best friend forever': 'bff',
    'bestuur voor lichamelijke opvoeding, sport en openluchtleven': 'Bloso',
    'betaaldvoetbalorganisatie': 'bvo',
    'betekenis': 'bet.',
    'betekenissen': 'bett.',
    'betreffende': 'betr.',
    'betrekkelijk': 'betr.',
    'bevordering integriteitsbeoordelingen door het openbaar bestuur': 'Bibob',
    'bevordering zonder kosten': 'b.z.k.',
    'bewust alleenstaande moeder': 'bam',
    'bewust onbeschonken bestuurder': 'bob',
    'bewust ongehuwde moeder': 'bom',
    'bewust ongehuwde vader': 'bov',
    'bezinkingssnelheid van erytrocyten': 'bse',
    'bezoekers niet opgekomen': 'b.n.o.',
    'bh': 'beha',
    'bicycle motocross': 'BMX',
    'biedt zich aan': 'b.z.a.',
    'bier voor onderweg': 'bvo',
    'bij geen gehoor': 'b.g.g.',
    'bij leven en welzijn': 'b.l.e.w.',
    'bij voorbaat dank': 'b.v.d.',
    'bij voorbaat hartelijk dank': 'b.v.h.d.',
    'bijgaand': 'bijg.',
    'bijvoeglijk': 'bijv.',
    'bijvoeglijk naamwoord': 'bijv. nw.',
    'bijvoorbeeld': 'bv.',
    'bijwoord': 'bijw.',
    'bijwoordelijk': 'bijw.',
    'bijzonder': 'bijz.',
    'bijzonder academisch personeel': 'BAP',
    'bijzonder onderwijs': 'bo',
    'bijzonder plan van aanleg': 'BPA',
    'bijzondere opsporingsbrigade': 'BOB',
    'bijzondere verbruiksbelasting': 'bvb',
    'bilateraal overleg': 'bila',
    'binnenlandse strijdkrachten': 'BS',
    'binnenlandse veiligheidsdienst': 'BVD',
    'biologisch-dynamisch': 'bd',
    'bitterbal': 'biba',
    'black, indigenous, people of color': 'bipoc',
    'bladzijde': 'blz.',
    'blind carbon copy': 'bcc',
    'body dysmorphic disorder': 'BDD',
    'bodymassindex': 'BMI',
    'boerburgerbeweging': 'BBB',
    'boerenpartij': 'BP',
    'bof, mazelen, rodehond': 'bmr',
    'bonaire, sint-eustatius en saba': 'BES',
    'bond beter leefmilieu': 'BBL',
    'bond van bedienden, technici en kaders': 'BBTK',
    'bond van grote en jonge gezinnen': 'BGJG',
    'bondage and discipline, dominance and submission, sadism and masochism': 'bdsm',
    'boviene spongiforme encefalopathie': 'BSE',
    'brazil, russia, india, china': 'BRIC',
    'brazil, russia, india, china, south africa': 'BRICS',
    'british broadcasting corporation': 'BBC',
    'broadcast music incorporated': 'BMI',
    'bruto': 'bro.',
    'bruto binnenlands product': 'bbp',
    'bruto nationaal inkomen': 'bni',
    'bruto nationaal product': 'bnp',
    'brutovloeroppervlak': 'bvo',
    'btw-identificatienummer': 'btw-ID',
    'buik, billen, benen': 'bbb',
    'buiten dienst': 'b.d.',
    'buitengewoon ambtenaar van de burgerlijke stand': 'babs',
    'buitengewoon basisonderwijs': 'bubao',
    'buitengewoon lager onderwijs': 'blo',
    'buitengewoon onderwijs': 'buo',
    'buitengewoon opsporingsambtenaar': 'boa',
    'buitengewoon secundair onderwijs': 'buso',
    'buitenschoolse opvang': 'bso',
    'bureau kredietregistratie': 'BKR',
    'bureau openbare gezondheidszorg': 'BOG',
    'bureau voor muziek': 'Buma',
    'burgemeester en wethouders': 'B en W',
    'burgermannetje': 'buma',
    'burgerservicenummer': 'bsn',
    'business-to-administration': 'b2a',
    'business-to-business': 'b2b',
    'business-to-consumer': 'b2c',
    'bustehouder': 'bh',
    'buurtinformatienetwerk': 'bin',
    'buy now, pay later': 'BNPL',
    'by the way': 'btw',
    'carbon copy': 'cc',
    'cardiopulmonary ressusitation': 'cpr',
    'caribbean community': 'Caricom',
    'casu quo': 'c.q.',
    'catalogus': 'cat.',
    'categorie': 'cat.',
    'centraal': 'centr.',
    'centraal bureau levensmiddelenhandel': 'CBL',
    'centraal bureau voor burgerzaken': 'CBB',
    'centraal bureau voor de statistiek': 'CBS',
    'centraal bureau voor rijvaardigheidsbewijzen': 'CBR',
    'centraal college': 'cc',
    'centraal financieringsorgaan': 'CFO',
    'centraal informatiepunt onderzoek telecommunicatie': 'CIOT',
    'centraal instituut voor toetsontwikkeling': 'Cito',
    'centraal orgaan opvang asielzoekers': 'COA',
    'centraal orgaan verklaring omtrent het gedrag': 'COVOG',
    'centraal planbureau': 'CPB',
    'centraal station': 'CS',
    'central intelligence agency': 'CIA',
    'central processing unit': 'CPU',
    'centrale antenne-inrichting': 'cai',
    'centrale ondernemingsraad': 'cor',
    'centrale raad voor het bedrijfsleven': 'CRB',
    'centrale slaapapneu': 'CSA',
    'centrale verwarming': 'cv',
    'centraleslaapapneusyndroom': 'CSAS',
    'centrum': 'centr.',
    'centrum algemeen welzijnswerk': 'CAW',
    'centrumdemocraten': 'CD',
    'centrumpartij': 'CP',
    'centrumpartij \'86': 'CP\'86',
    'cerebrale parese': 'CP',
    'cerebrovasculair accident': 'CVA',
    'charmant': 'charm.',
    'chief accounting officer': 'CAO',
    'chief administrative officer': 'CAO',
    'chief analytics officer': 'CAO',
    'chief data officer': 'CDO',
    'chief executive officer': 'CEO',
    'chief financial officer': 'CFO',
    'chief hybrid officer': 'CHO',
    'chief information officer': 'CIO',
    'chief information security officer': 'CISO',
    'chief privacy officer': 'CPO',
    'chief technical officer': 'CTO',
    'chief technology officer': 'CTO',
    'chloorfluorkoolwaterstof': 'cfk',
    'christelijk': 'chr.',
    'christelijk nationaal vakverbond': 'CNV',
    'christelijk onderwijzersverbond': 'COV',
    'christelijke centrale van de openbare diensten': 'CCOD',
    'christelijke federatie overheidspersoneel': 'CFO',
    'christelijke volkspartij': 'CVP',
    'christen democratisch appèl': 'CDA',
    'christen-democratisch en vlaams': 'CD&V',
    'christenunie': 'CU',
    'christus': 'Chr.',
    'chronic obstructive pulmonary disease': 'COPD',
    'chronische aspecifieke respiratoire aandoeningen': 'cara',
    'chronischevermoeidheidssyndroom': 'CVS',
    'circa': 'c.',
    'circa': 'c.',
    'cito-toets': 'Cito',
    'clustered regularly interspaced short palindromic repeats': 'CRISPR',
    'collectief contract': 'cc',
    'collectieve arbeidsovereenkomst': 'cao',
    'college bescherming persoonsgegevens': 'CBP',
    'college financieel toezicht': 'Cft',
    'college van beheer': 'cvb',
    'college van bestuur': 'CvB',
    'college van burgemeester en schepenen': 'CBS',
    'colombia broadcasting system': 'CBS',
    'commanditaire vennootschap': 'cv',
    'commissariaat voor de media': 'CvdM',
    'commissaris der koningin': 'CdK',
    'commissaris des konings': 'CdK',
    'commissie': 'cie.',
    'commissie van toezicht': 'cvt',
    'commissie voor inlichtingen- en veiligheidsdiensten': 'CIVD',
    'communistische partij van nederland': 'CPN',
    'community of latin american and caribbean states': 'CELAC',
    'compact disc': 'cd',
    'compact disc- recordable': 'cd-r',
    'compact disc-interactive': 'cd-i',
    'compagnie': 'cie.',
    'compagniescommandant': 'cc',
    'comparatief': 'comp.',
    'comparativus': 'comp.',
    'compressed natural gas': 'cng',
    'computer-aided instruction': 'CAI',
    'computertoets \'control\'': 'ctrl',
    'computervisiesyndroom': 'CVS',
    'confer': 'cfr.',
    'conferentie over veiligheid en samenwerking in europa': 'CVSE',
    'conjunctie': 'conj.',
    'conjunctivus': 'conj.',
    'consul': 'cons.',
    'consumentenprijsindex': 'CPI',
    'continu variabele transmissie': 'cvt',
    'continuing airworthiness management organisation': 'camo',
    'controlecommissie': 'cc',
    'coronavirus disease': 'covid',
    'coronavirus disease 2019': 'COVID-19',
    'corps diplomatique': 'CD',
    'covid safe ticket': 'CST',
    'coöperatieve vennootschap': 'cv',
    'coöperatieve vennootschap met beperkte aansprakelijkheid': 'cvba',
    'criminele burgerinfiltrant': 'cbi',
    'cruise lines international association': 'CLIA',
    'cultureel centrum': 'cc',
    'cultureel jongerenpaspoort': 'CJP',
    'cultuur- en ontspanningscentrum': 'COC',
    'curriculum vitae': 'cv',
    'dagelijks bestuur': 'db',
    'dat is': 'd.i.',
    'dat wil zeggen': 'd.w.z.',
    'dat zijn': 'd.z.',
    'datief': 'dat.',
    'dativus': 'dat.',
    'de dato': 'd.d.',
    'de heer': 'dhr.',
    'de nationale assemblee': 'DNA',
    'de nederlandsche bank': 'DNB',
    'debet': 'deb.',
    'december': 'dec',
    'deeltijds beroepssecundair onderwijs': 'dbso',
    'deeltijds kunstonderwijs': 'dko',
    'deeltijds onderwijs': 'do',
    'deelwoord': 'deelw.',
    'democraten 66': 'D66',
    'deo volente': 'D.V.',
    'deoxyribonucleic acid': 'DNA',
    'derde arbeidscircuit': 'DAC',
    'derde industriële revolutie in vlaanderen': 'DIRV',
    'derde wereldoorlog': 'WO III',
    'dergelijk': 'dgl.',
    'desktoppublishing': 'dtp',
    'deux-chevaux': '2cv',
    'di-ethylmetatolueenamide': 'DEET',
    'di-ethylstilbestrol': 'des',
    'diagnose-behandelcombinatie': 'dbc',
    'diagnose-behandelingcombinatie': 'dbc',
    'dichloordifenyltrichloorethaan': 'DDT',
    'dictionnaire explicatif et combinatoire': 'DEC',
    'dienstdoend': 'dd.',
    'difterie, kinkhoest, tetanus, polio': 'dktp',
    'difterie, tetanus, polio': 'dtp',
    'digital audio broadcasting': 'DAB',
    'digital equipment corporation': 'DEC',
    'digital object identifier': 'DOI',
    'digital subscriber line': 'DSL',
    'digital versatile disk': 'dvd',
    'dimethylether': 'DME',
    'dimethylsulfide': 'DMS',
    'dinsdag': 'di.',
    'direct message': 'dm',
    'directeur-generaal': 'dg',
    'directeur-grootaandeelhouder': 'dga',
    'disability-adjusted life year': 'daly',
    'diskjockey': 'dj',
    'districtscommissaris': 'dc',
    'dit is': 'd.i.',
    'divers': 'div.',
    'dividend': 'div.',
    'divisie': 'div.',
    'dj': 'deejay',
    'doctor': 'dr.',
    'doctor juris utriusque': 'd.j.u.',
    'doctoranda': 'dra.',
    'doctorandus': 'drs.',
    'domain name server': 'DNS',
    'dominee': 'ds.',
    'donderdag': 'do',
    'door middel van': 'd.m.v.',
    'dots per inch': 'dpi',
    'drie dimensies': '3D',
    'driedimensionaal': '3D',
    'dynamic random-access memory': 'DRAM',
    'earnings before interest and taxation': 'ebit',
    'earnings before interest, taxes and and amortisation': 'ebita',
    'earnings before interest, taxes, depreciation and amortisation': 'ebitda',
    'economische controledienst': 'ECD',
    'economische en monetaire unie': 'EMU',
    'ecstasy': 'xtc',
    'een en ander': 'e.e.a.',
    'eenmansvennootschap met beperkte aansprakelijkheid': 'eba',
    'eenpersoons besloten vennootschap met beperkte aansprakelijkheid': 'ebvba',
    'eenvoudig technisch onderwijs': 'eto',
    'eerste hulp bij ongelukken': 'EHBO',
    'eerste kamer': 'E.K.',
    'eerste kwartier': 'e.k.',
    'eerste wereldoorlog': 'WO I',
    'eerstkomend': 'e.k.',
    'eerwaarde': 'eerw.',
    'eigen doelpunt': 'e.d.',
    'electric vehicle': 'EV',
    'electronic data processing': 'EDP',
    'electronic travel authorisation': 'ETA',
    'elektro-encefalogram': 'eeg',
    'elektrocardiogram': 'ecg',
    'elektroconvulsietherapie': 'ect',
    'elektromagnetische puls': 'emp',
    'elektronisch patiëntendossier': 'epd',
    'elektronische identiteitskaart': 'e-ID',
    'elektronische publicatieomgeving': 'EPO',
    'elementair beroepsonderwijs': 'ebo',
    'emeritus': 'em.',
    'eminentie': 'em.',
    'emotional quotient': 'EQ',
    'en andere': 'e.a.',
    'en anderen': 'e.a.',
    'en dergelijke': 'e.d.',
    'en dergelijke meer': 'e.d.m.',
    'en omgeving': 'e.o.',
    'en omstreken': 'e.o.',
    'en vele andere': 'e.v.a.',
    'en volgende': 'e.v.',
    'energieprestatiecertificaat': 'epc',
    'enhanced messaging service': 'EMS',
    'enkelvoud': 'enk.',
    'enterprise resource planning': 'ERP',
    'entertainment software rating board': 'ESRB',
    'enzovoort': 'enz.',
    'enzovoorts': 'enz.',
    'epidermolysis bullosa': 'EB',
    'erytropoëtine': 'epo',
    'erytropoëtische protoporfyrie': 'EPP',
    'escherichia coli': 'E. coli',
    'espresso-martini': 'esma',
    'estimated time of arrival': 'ETA',
    'et alii': 'et al.',
    'et cetera': 'etc.',
    'ethyleencopolymeerbitumen': 'ecb',
    'euro banking association': 'EBA',
    'euro interbank offered rate': 'Euribor',
    'europe, middle east en africa': 'EMEA',
    'european banking authority': 'EBA',
    'european boxing association': 'EBA',
    'european currency unit': 'ecu',
    'european insurance and occupational pensions authority': 'EIOPA',
    'european patent office': 'EPO',
    'european securities and markets authority': 'ESMA',
    'european systemic risk board': 'ESRB',
    'europees kampioenschap': 'EK',
    'europees parlement': 'EP',
    'europees sociaal fonds': 'ESF',
    'europese centrale bank': 'ECB',
    'europese economische gemeenschap': 'EEG',
    'europese economische ruimte': 'EER',
    'europese gemeenschap': 'EG',
    'europese gemeenschap voor atoomenergie': 'EGA',
    'europese gemeenschap voor kolen en staal': 'EGKS',
    'europese unie': 'EU',
    'europese voetbalbond': 'UEFA',
    'europese vrijhandelsassociatie': 'EVA',
    'euskadi ta askatasuna': 'ETA',
    'evangelische omroep': 'EO',
    'eventueel': 'evt.',
    'everything but arms': 'EBA',
    'excellentie': 'Exc.',
    'exclusief': 'excl.',
    'extended play': 'ep',
    'extensie': 'htm',
    'extra begeleiding en toezichtlocatie': 'ebtl',
    'extra beveiligde inrichting': 'ebi',
    'extra extra extra large': 'XXXL',
    'extra extra extra small': 'XXXS',
    'extra extra large': '2XL',
    'extra extra small': 'XXS',
    'extra large': 'XL',
    'extra small': 'XS',
    'familie': 'fam.',
    'fasciculum': 'fasc.',
    'fascikel': 'fasc.',
    'februari': 'feb',
    'federal bureau of investigation': 'FBI',
    'federale overheidsdienst': 'FOD',
    'federatie nederlandse vakbeweging': 'FNV',
    'fifth generation': '5G',
    'figuur': 'fig.',
    'finland': 'Fin.',
    'firma': 'fa.',
    'first generation': '1G',
    'first in, first out': 'fifo',
    'fiscale beleggingsinstelling': 'fbi',
    'fiscale inlichtingen- en opsporingsdienst': 'FIOD',
    'flight test engineer': 'FTE',
    'fonds voor wetenschappelijk onderzoek': 'FWO',
    'food and agriculture organization of the united nations': 'FAO',
    'football club': 'FC',
    'for your information': 'fyi',
    'forensisch psychiatrische dienst': 'FPD',
    'former yugoslav republic of macedonia': 'FYROM',
    'formule 1': 'F1',
    'forum voor democratie': 'FVD',
    'fourth generation': '4G',
    'fourwheeldrive': '4wd',
    'frames per seconde': 'fps',
    'frank': 'fr.',
    'frater': 'fr.',
    'free alongside ship': 'f.a.s.',
    'free on board': 'f.o.b.',
    'freie demokratische partei': 'FDP',
    'frequentiemodulatie': 'FM',
    'frequently asked question': 'FAQ',
    'friend with benefits': 'fwb',
    'front démocratique des francophones': 'FDF',
    'fuerzas armadas revolucionarias de colombia': 'FARC',
    'fulltime-equivalent': 'fte',
    'futurum': 'fut.',
    'fédération internationale de football association': 'FIFA',
    'fédération internationale de natation': 'FINA',
    'fédération internationale des échecs': 'FIDE',
    'gammahydroxybutyraat': 'GHB',
    'gas, water, licht': 'g.w.l.',
    'gebiedsgebonden politiefunctionaris': 'gpf',
    'gebonden': 'geb.',
    'geboren': 'geb.',
    'gebroeders': 'gebr.',
    'gedifferentieerd tarief': 'diftar',
    'geen meervoud': 'g.mv.',
    'geestelijke gezondheidszorg': 'ggz',
    'gehypothekeerde capaciteit': 'hycap',
    'gelegen': 'gel.',
    'gemeenschappelijk administratiekantoor': 'GAK',
    'gemeente': 'gem.',
    'gemeentelijk energiebedrijf': 'GEB',
    'gemeentelijk onderwijsachterstandenbeleid': 'goa',
    'gemeentelijk ruimtelijk uitvoeringsplan': 'GRUP',
    'gemeentelijke geneeskundige dienst': 'GGD',
    'gemeentelijke geneeskundige en gezondheidsdienst': 'GG en GD',
    'gemeentelijke sociale dienst': 'GSD',
    'gemenebest van onafhankelijke staten': 'GOS',
    'gemeubileerd': 'gem.',
    'gemiddeld': 'gem.',
    'gemodificeerde radicale mastectomie': 'grm',
    'geneesmiddelenvergoedingssysteem': 'GVS',
    'generaal': 'gen.',
    'general agreement on tariffs and trade': 'GATT',
    'general data protection regulation': 'GDPR',
    'general packet radio service': 'GPRS',
    'genetically modified organism': 'gmo',
    'genetisch gemodificeerd organisme': 'ggo',
    'genitief': 'gen.',
    'genitivus': 'gen.',
    'gerechtelijk vooronderzoek': 'gvo',
    'gerechtelijk-geneeskundige dienst': 'GGD',
    'gereformeerd politiek verbond': 'GPV',
    'gestorven': 'gest.',
    'gesubsidieerde contractueel': 'geco',
    'gevolmachtigde minister': 'GevMin',
    'gevraagd': 'gevr.',
    'gewestelijk arbeidsbureau': 'GAB',
    'gewestelijke ontwikkelingsmaatschappij': 'GOM',
    'gewone commanditaire vennootschap': 'gcv',
    'gewoon lager onderwijs': 'glo',
    'globaal medisch dossier': 'gmd',
    'global positioning system': 'gps',
    'global positioning system)': 'gps',
    'global system for mobile communications': 'gsm',
    'global system for mobile communications': 'gsm',
    'goed': 'g',
    'gram': 'gr.',
    'grand prix': 'GP',
    'graphics interchange format': 'gif',
    'graphics processing unit': 'GPU',
    'greatest of all time': 'GOAT',
    'groenlinks': 'GL',
    'groente-, fruit- en tuinafval': 'gft',
    'groep van acht': 'G8',
    'groep van zeven': 'G7',
    'groepsondernemingsraad': 'gor',
    'grootste gemene deler': 'g.g.d.',
    'gulden': 'gld.',
    'haagse scheidsrechtersvereniging': 'HSV',
    'haars inziens': 'h.i.',
    'halfopen bebouwing': 'hob',
    'hamburger sport-verein': 'HSV',
    'hare koninklijke hoogheid': 'H.K.H.',
    'hare koninklijke majesteit': 'H.K.M.',
    'hartelijk gefeliciteerd': 'h.g.',
    'hartelijke groet': 'h.g.',
    'heer': 'hr.',
    'heilige': 'H.',
    'heilige mis': 'H. Mis',
    'heiligen': 'HH.',
    'heilpedagogisch verbond': 'HPV',
    'hemoglobine': 'Hb',
    'hepatitis a-virus': 'HAV',
    'hepatitis b-virus': 'HBV',
    'hepatitis c-virus': 'HCV',
    'hepatitis d-virus': 'HDV',
    'hepatitis e-virus': 'HEV',
    'hepatitis f-virus': 'HFV',
    'hepatitis g-virus': 'HGV',
    'heren': 'HH.',
    'herpes-simplexvirus': 'HSV',
    'het alternatief': 'Halt',
    'het brabants orkest': 'HBO',
    'heupdysplasie': 'HD',
    'high definition': 'hd',
    'high potential': 'hipo',
    'high-definition': 'hd',
    'high-definition multimedia interface': 'HDMI',
    'high-definition televisie': 'hd-tv',
    'high-frequency trading': 'HFT',
    'hogedefinitietelevisie': 'hdtv',
    'hoger algemeen voortgezet onderwijs': 'havo',
    'hoger beroepsonderwijs': 'hbo',
    'hoger beroepssecundair onderwijs': 'hbso',
    'hoger economisch en administratief onderwijs': 'heao',
    'hoger onderwijs buiten de universiteit': 'hobu',
    'hoger onderwijs van het korte type': 'hokt',
    'hoger onderwijs van het lange type': 'holt',
    'hoger secundair onderwijs': 'hso',
    'hogere beroepsopleiding verpleegkundigen': 'hbo-v',
    'hogere burgerschool': 'hbs',
    'hogere landbouwschool': 'hls',
    'hogere technische school': 'hts',
    'hogesnelheidslijn': 'hsl',
    'hogesnelheidstrein': 'hst',
    'holographic versatile disc': 'hvd',
    'home box office': 'HBO',
    'homo, lesbienne, biseksueel': 'holebi',
    'homo-ontmoetingsplaats': 'HOP',
    'hoofd': 'hfd.',
    'hoofdstuk': 'hfst.',
    'hoog rendement': 'hr',
    'hoogste klasse in (o.a.) karate, kungfu en kickboksen': 'K-1',
    'hubble space telescope': 'HST',
    'huisartsengroep': 'hagro',
    'hulporganisatie zuid-oost azië': 'ZOA',
    'humaan metapneumovirus': 'hMPV',
    'humaan papillomavirus': 'HPV',
    'human immunodeficiency virus': 'hiv',
    'human resources': 'hr',
    'humanresourcesmanagement': 'hrm',
    'huns inziens': 'h.i.',
    'hyper text markup': 'HTM',
    'hypertext markup language': 'HTML',
    'hypertext transfer protocol': 'http',
    'i don\'t know': 'idk',
    'ibidem': 'ibid.',
    'id est': 'i.e.',
    'idem': 'id.',
    'identificatie': 'ID',
    'iemand met een \'not in my backyard\'-houding': 'nimby',
    'implanteerbare cardioverter-defibrillator': 'icd',
    'in bezit van': 'i.b.v.',
    'in casu': 'i.c.',
    'in combinatie met': 'i.c.m.',
    'in geval van': 'i.g.v.',
    'in het algemeen': 'i.h.a.',
    'in het bijzonder': 'i.h.b.',
    'in het kader van': 'i.h.k.v.',
    'in ieder geval': 'i.i.g.',
    'in opdracht': 'i.o.',
    'in opdracht van': 'i.o.v.',
    'in oprichting': 'i.o.',
    'in overleg': 'i.o.',
    'in overleg met': 'i.o.m.',
    'in plaats van': 'i.p.v.',
    'in real life': 'irl',
    'in samenwerking met': 'i.s.m.',
    'in tegenstelling tot': 'i.t.t.',
    'in verband met': 'i.v.m.',
    'in voce': 'i.v.',
    'in zeer goede staat': 'i.z.g.st.',
    'in-vitrofertilisatie': 'ivf',
    'inbewaringstelling': 'ibs',
    'inclusief': 'incl.',
    'index': 'ind.',
    'india pale ale': 'IPA',
    'indicatief': 'ind.',
    'indicativus': 'ind.',
    'individueel beroepsonderwijs': 'ibo',
    'individueel landbouwonderwijs': 'ilo',
    'individueel voortgezet onderwijs': 'ivo',
    'industrial and commerical bank of china': 'ICBC',
    'infinitief': 'inf.',
    'infinitivus': 'inf.',
    'informatie beheer groep': 'IBG',
    'informatie- en communicatietechnologie': 'ICT',
    'informatietechnologie': 'IT',
    'ingenieur': 'ing.',
    'ingenieur': 'ir.',
    'inhoud': 'inh.',
    'initial public offering': 'IPO',
    'inkomstenbelasting': 'ib',
    'inlogcode': 'DigiD',
    'instant messaging': 'IM',
    'integrated services digital network': 'ISDN',
    'intelligent design': 'ID',
    'intelligentiequotiënt': 'IQ',
    'intensive care': 'ic',
    'intercity': 'IC',
    'intern verzelfstandigd agentschap': 'iva',
    'internationaal': 'int.',
    'internationaal monetair fonds': 'IMF',
    'internationaal olympisch comité': 'IOC',
    'international association of athletics federations': 'IAAF',
    'international bank account number': 'IBAN',
    'international film festival rotterdam': 'IFFR',
    'international football association board': 'IFAB',
    'international matchpoint': 'imp',
    'international phonetic alphabet': 'IPA',
    'international standard book number': 'ISBN',
    'internetprotocol': 'IP',
    'internetserviceprovider': 'isp',
    'interparlementair koninkrijksoverleg': 'IPKO',
    'interprofessioneel akkoord': 'ipa',
    'intra-uteriene inseminatie': 'iui',
    'intracytoplasmatische sperma-injectie': 'icsi',
    'intransitief': 'intr.',
    'intraveneus': 'iv',
    'inzake': 'inz.',
    'inzonderheid': 'inz.',
    'irish republican army': 'IRA',
    'islamitische staat': 'IS',
    'italiaans': 'It.',
    'italië': 'It.',
    'item': 'it.',
    'jaargang': 'jg.',
    'jaarlijks kostenpercentage': 'jkp',
    'januari': 'jan',
    'jeugdherberg': 'JH',
    'jezus christus': 'J.C.',
    'jodiumhoudend broodzout': 'jobrozo',
    'joint strike fighter': 'JSF',
    'joint strike fighter': 'JSF',
    'jongeren advies centrum': 'JAC',
    'jongstleden': 'jl.',
    'jonkheer': 'jhr.',
    'jonkvrouw': 'jkvr.',
    'judobond nederland': 'JBN',
    'juffrouw': 'juffr.',
    'juli': 'jul',
    'juni': 'jun',
    'junior': 'jr.',
    'just a minute': 'jam',
    'justitiële jeugdinrichting': 'jji',
    'kadastraal inkomen': 'ki',
    'kadastraal nummer': 'kad. nr.',
    'kamer van inbeschuldigingstelling': 'KIB',
    'kamer van koophandel': 'KVK',
    'kamers voor handel en nijverheid': 'KHN',
    'kanker': 'k',
    'katholiek militair tehuis': 'kmt',
    'katholiek vormingswerk van landelijke vrouwen': 'KVLV',
    'katholieke landelijke jeugd': 'KLJ',
    'katholieke radio omroep': 'KRO',
    'katholieke studentenactie': 'KSA',
    'keel-, neus- en oor­heel­kun­de': 'kno',
    'kennismakingstijd': 'kmt',
    'keuken, douche, toilet': 'k.d.t.',
    'keuring van elektrotechnische materialen arnhem': 'KEMA',
    'kind van ouders met psychische problemen': 'KOPP',
    'kinderdagverblijf': 'kdv',
    'kinderen niet toegelaten': 'KNT',
    'kinderen toegelaten': 'KT',
    'klachten aan arm, nek en/of schouder': 'KANS',
    'klein chemisch afval': 'kca',
    'klein gevaarlijk afval': 'kga',
    'kleine of middelgrote onderneming': 'kmo',
    'kleurentelevisie': 'ktv',
    'klote': 'k',
    'knock-out': 'ko',
    'knooppunt': 'knp.',
    'kohier': 'koh.',
    'kolom': 'kol.',
    'komitet gosudarstvennoj bezopasnosti': 'KGB',
    'koninklijk': 'kon.',
    'koninklijk belgisch verbond voor bescherming van de vogels': 'KBVBV',
    'koninklijk belgisch volleybalverbond': 'KBVBV',
    'koninklijk besluit': 'KB',
    'koninklijk meteorologisch instituut': 'KMI',
    'koninklijk nederlands meteorologisch instituut': 'KNMI',
    'koninklijk nederlandsch-indisch leger': 'KNIL',
    'koninklijk warmbloed paardenstamboek nederland': 'KWPN',
    'koninklijke belgische atletiekbond': 'KBAB',
    'koninklijke belgische basketbalbond': 'KBBB',
    'koninklijke belgische hockeybond': 'KBHB',
    'koninklijke belgische ruitersportfederatie': 'KBRSF',
    'koninklijke belgische skifederatie': 'KBSF',
    'koninklijke belgische snelschaatsfederatie': 'KBSF',
    'koninklijke belgische tennisbond': 'KBTB',
    'koninklijke belgische turnbond': 'KBTB',
    'koninklijke belgische voetbalbond': 'KBVB',
    'koninklijke belgische wielrijdersbond': 'KBWB',
    'koninklijke belgische zwembond': 'KBZB',
    'koninklijke bibliotheek': 'KB',
    'koninklijke horeca nederland': 'KHN',
    'koninklijke militaire academie': 'KMA',
    'koninklijke militaire school': 'KMS',
    'koninklijke nationale strijdersbond van belgië': 'KNSB',
    'koninklijke nederlands watersportverbond': 'KNWV',
    'koninklijke nederlandsche roeibond': 'KNRB',
    'koninklijke nederlandsche schaatsrijdersbond': 'KNSB',
    'koninklijke nederlandsche wielrenunie': 'KNWU',
    'koninklijke nederlandse akademie van wetenschappen': 'KNAW',
    'koninklijke nederlandse atletiekunie': 'KNAU',
    'koninklijke nederlandse biljartbond': 'KNBB',
    'koninklijke nederlandse cricketbond': 'KNCB',
    'koninklijke nederlandse hippische sportfederatie': 'KNHS',
    'koninklijke nederlandse hockeybond': 'KNHB',
    'koninklijke nederlandse jagersvereniging': 'KNJV',
    'koninklijke nederlandse lawn tennis bond': 'KNLTB',
    'koninklijke nederlandse luchtvaarmaatschappij': 'KLM',
    'koninklijke nederlandse schaakbond': 'KNSB',
    'koninklijke nederlandse schietsport associatie': 'KNSA',
    'koninklijke nederlandse vereniging voor ehbo': 'KNV EHBO',
    'koninklijke nederlandse voetbalbond': 'KNVB',
    'koninklijke nederlandse zwembond': 'KNZB',
    'koninklijke vlaamse schouwburg': 'KVS',
    'koninklijke voetbalclub kortrijk': 'KVK',
    'koolstofdioxide': 'CO₂',
    'korintiërs': 'Kor.',
    'korps landelijke politiediensten': 'KLPD',
    'kritische depositiewaarde': 'KDW',
    'kunstenaarscollectief': 'Cobra',
    'kunstmatige inseminatie': 'ki',
    'kunstmatige inseminatie met sperma van de eigen partner': 'kie',
    'kunstmatige intelligentie': 'ki',
    'kunstsecundair onderwijs': 'kso',
    'kut': 'k',
    'kwaliteit': 'kwal.',
    'l\'association des bibliophiles universels': 'ABU',
    'laatste kwartier': 'l.k.',
    'laatstgenoemde': 'lg.',
    'laatstleden': 'll.',
    'laboratorium voor bloembollenonderzoek': 'LBO',
    'lage-emissiezone': 'LEZ',
    'lager beroepsgericht onderwijs': 'lbgo',
    'lager beroepsonderwijs': 'lbo',
    'lager economisch en administratief onderwijs': 'leao',
    'lager huishoud- en nijverheidsonderwijs': 'lhno',
    'lager nijverheidsonderwijs': 'lno',
    'lager onderwijs': 'lo',
    'lager secundair onderwijs': 'lso',
    'lager technisch onderwijs': 'lto',
    'lagere technische school': 'lts',
    'landbouwhogeschool': 'LH',
    'landelijke studentenvakbond': 'LSVb',
    'landen en gebieden overzee': 'LGO',
    'langspeelplaat': 'lp',
    'large': 'L',
    'large language model': 'LLM',
    'last in, first out': 'lifo',
    'laughing out loud': 'lol',
    'lectori salutem': 'L.S.',
    'leefbaar rotterdam': 'LR',
    'leer- en opvoedingsmoeilijkheden': 'lom',
    'leerling': 'll.',
    'leerlingen': 'lln.',
    'leerwegondersteunend onderwijs': 'lwoo',
    'leraar in opleiding': 'lio',
    'lesbian, gay, bisexual, transgender': 'lgbt',
    'lesbian, gay, bisexual, transgender, queer, intersexual, asexual, pansexual': 'lgbtqiap',
    'lesbian, gay, bisexual, trans­gen­der, queer': 'lgbtq',
    'lesbian, gay, bisexual, trans­gen­der, queer and other': 'lgbtq+',
    'lesbian, gay, bisexual, trans­gen­der, queer, intersexual and other': 'lgbtqia+',
    'lesbienne, homo(seksueel), biseksueel, transgender, interseks(ueel), queer en overige': 'lhbtiq+',
    'lesbienne, homo, bi, transgender, queer, interseks(ueel), aseksueel': 'lhbtqia',
    'lesbienne, homo, bi, transgender, queer, interseks(ueel), aseksueel en overige': 'lhbtqia+',
    'lesbienne, homo, bi, transgender, queer, interseks(ueel), aseksueel, panseksueel': 'lhbtqiap',
    'lesbienne, homo, biseksueel, transgender': 'lhbt',
    'lesbienne, homo, biseksueel, transgender, interseks(ueel)': 'lhbti',
    'lesbienne, homo, biseksueel, transgender, interseks(ueel), queer, agender, panseksueel, cisgender en overige': 'lhbtiqapc+',
    'levenseinde informatieforum': 'LEIF',
    'liberaal': 'lib.',
    'licentiaat': 'lic.',
    'lichamelijke opvoeding': 'lo',
    'licht verstandelijk beperkt': 'lvb',
    'lichte verstandelijke beperking': 'lvb',
    'lid van de marva': 'marva',
    'lid van de volkspolizei': 'vopo',
    'light amplification by stimulated emission of radiation': 'laser',
    'light electric vehicle': 'LEV',
    'light-emitting diode': 'led',
    'lijst pim fortuyn': 'LPF',
    'liquefied petroleum gas': 'lpg',
    'liquid crystal display': 'lcd',
    'liquid natural gas': 'lng',
    'live-action role-playing': 'larp',
    'living apart together': 'lat',
    'local area network': 'LAN',
    'local exchange trading system': 'LETS',
    'locatie': 'loc.',
    'locatief': 'loc.',
    'locativus': 'loc.',
    'loco citato': 'l.c.',
    'loopbaanonderbreking': 'lbo',
    'luchtvaart- en ruimtevaarttechniek': 'LR',
    'ludduvuddu': 'ldvd',
    'luitenant': 'lt.',
    'lysergeenzuurdi-ethylamide': 'lsd',
    'maandag': 'ma',
    'maart': 'mrt',
    'maatschappij': 'Mij.',
    'machtiging tot voorlopig verblijf': 'mvv',
    'magnetic resonance imaging': 'MRI',
    'magnetisch noorden': 'MN',
    'make america great again': 'MAGA',
    'man of vrouw': 'm/v',
    'man of vrouw of iemand van een niet nader gespecificeerd geslacht': 'm/v/x',
    'managementteam': 'mt',
    'mannelijk': 'mnl.',
    'mannelijk of vrouwelijk': 'm/v',
    'mannelijk of vrouwelijk of van een niet nader gespecificeerd geslacht': 'm/v/x',
    'marine vrouwenafdeling': 'Marva',
    'master': 'ma',
    'master': 'M',
    'master of arts': 'MA',
    'master of business administration': 'MBA',
    'master of ceremonies': 'mc',
    'master of science': 'MSc',
    'master-na-bacheloropleiding': 'manaba',
    'master-na-masteropleiding': 'manama',
    'maximaal': 'max.',
    'maximum': 'max.',
    'medezeggenschapsraad': 'mr',
    'medisch-opvoedkundig bureau': 'MOB',
    'medium': 'M',
    'medium density fibreboard': 'mdf',
    'meer uitgebreid lager onderwijs': 'mulo',
    'meervoud': 'mv.',
    'meester': 'mr.',
    'mejuffrouw': 'mej.',
    'meldplicht ongebruikelijke transacties': 'MOT',
    'meldpunt ongebruikelijke transacties': 'MOT',
    'menstruatieproductenuitgiftepunt': 'MUP',
    'met andere woorden': 'm.a.w.',
    'met behulp van': 'm.b.v.',
    'met bericht van verhindering': 'm.b.v.v.',
    'met betrekking tot': 'm.betr.t.',
    'met hartelijke dank': 'm.h.d.',
    'met hartelijke deelneming': 'm.h.d.',
    'met inbegrip van': 'm.i.v.',
    'met ingang van': 'm.i.v.',
    'met medewerking van': 'm.m.v.',
    'met name': 'm.n.',
    'met uitzondering van': 'm.u.v.',
    'met vriendelijke groet': 'm.v.g.',
    'methyleendioxymethylamfetamine': 'MDMA',
    'metriek stelsel': 'ms',
    'mevrouw': 'mevr.',
    'middelbaar algemeen voortgezet onderwijs': 'mavo',
    'middelbaar beroepsonderwijs': 'mbo',
    'middelbaar economisch en administratief onderwijs': 'meao',
    'middelbaar onderwijs': 'mo',
    'middelbaar onderwijs a': 'mo A',
    'middelbaar onderwijs b': 'mo B',
    'middelbare meisjesschool': 'mms',
    'middelbare technische school': 'mts',
    'middeleeuwen': 'ME',
    'midden- en kleinbedrijf': 'mkb',
    'middle east respiratory syndrome': 'MERS',
    'middle-aged man in lycra': 'mamil',
    'mijns inziens': 'm.i.',
    'milieucontainer': 'milco',
    'militair': 'mil.',
    'militaire inlichtingen- en veiligheidsdienst': 'MIVD',
    'militaire politie': 'MP',
    'militaire vrouwenafdeling': 'Milva',
    'miljard': 'mld.',
    'miljoen': 'mln.',
    'millennial yup': 'mup',
    'minderwaardigheidscomplex': 'minco',
    'minidisc': 'md',
    'minimaal': 'min.',
    'minimum': 'min.',
    'minister': 'min.',
    'minister-president': 'mp',
    'ministerie': 'min.',
    'ministerie van verkeer en waterstaat': 'V&W',
    'ministerieel besluit': 'MB',
    'mister': 'Mr',
    'mitochondriaal dna': 'mtDNA',
    'mixed martial arts': 'MMA',
    'mobiele eenheid': 'ME',
    'mobiele opsporingsbrigade': 'MOB',
    'model of human occupation': 'moho',
    'moeilijk lerende kinderen': 'mlk',
    'moeilijk opvoedbare kinderen': 'mok',
    'mond-en-klauwzeer': 'MKZ',
    'monseigneur': 'mgr.',
    'monsieur': 'Mr',
    'mother i\'d like to fuck': 'milf',
    'motorische remedial teaching': 'MRT',
    'motorschip': 'ms',
    'motortorpedoboot': 'mtb',
    'mountainbike': 'MTB',
    'moving pic­tures ex­perts group, layer three; geluidsbestand': 'mp3',
    'multimedia messaging service': 'mms',
    'multiple complex developmental disorder': 'MCDD',
    'multiple sclerose': 'MS',
    'multipurpose vehicle': 'MPV',
    'mutatis mutandis': 'm.m.',
    'myalgische encefalomyelitis': 'ME',
    'myocardinfarct': 'MI',
    'na christus': 'n.Chr.',
    'naamloze vennootschap': 'nv',
    'naar aanleiding van': 'n.a.v.',
    'nader overeen te komen': 'n.o.t.k.',
    'nader te bepalen': 'n.t.b.',
    'namelijk': 'nl.',
    'namiddag': 'nm.',
    'naschoolse opvang': 'nso',
    'nationaal centrum voor ontwikkelingssamenwerking': 'NCOS',
    'nationaal christelijk middenstandsverbond': 'NCMV',
    'nationaal coördinator tegen discriminatie en racisme': 'NCDR',
    'nationaal coördinator terrorismebestrijding': 'NCTb',
    'nationaal coördinator terrorismebestrijding': 'NCTb',
    'nationaal coördinator terrorismebestrijding en veiligheid': 'NCTV',
    'nationaal coördinator terrorismebestrijding en veiligheid': 'NCTV',
    'nationaal inkomen': 'ni',
    'nationaal instituut voor budgetvoorlichting': 'Nibud',
    'nationaal onderzoeksprogramma verdroging': 'NOV',
    'nationaal record': 'nr',
    'nationaal-socialistische beweging': 'NSB',
    'national aeronautics and space administration': 'NASA',
    'national rifle association': 'NRA',
    'national security agency': 'NSA',
    'nationale bank van belgië': 'NBB',
    'nationale maatschappij der belgische spoorwegen': 'NMBS',
    'nationale maatschappij van buurtspoorwegen': 'NMVB',
    'nationale partij suriname': 'NPS',
    'natuurtechnisch instituut': 'NATIN',
    'nea dimokratia': 'ND',
    'nederland': 'Nl.',
    'nederlands': 'Nl.',
    'nederlands als eerste taal': 'NT1',
    'nederlands als tweede taal': 'NT2',
    'nederlands bijbelgenootschap': 'NBG',
    'nederlands dagblad': 'ND',
    'nederlands impresariaat': 'NI',
    'nederlands instituut voor forensische psychiatrie en psychologie': 'NIFP',
    'nederlands instituut voor oorlogsdocumentatie': 'NIOD',
    'nederlands instituut voor publieke opinie': 'NIPO',
    'nederlands instituut voor zeeonderzoek': 'NIOZ',
    'nederlands kampioenschap': 'NK',
    'nederlands katholiek vakverbond': 'NKV',
    'nederlands olympisch comité': 'NOC',
    'nederlands reclame archief': 'NRA',
    'nederlands register gerechtelijk deskundigen': 'NRGD',
    'nederlands verbond van vakverenigingen': 'NVV',
    'nederlandsche handel-maatschappij': 'NHM',
    'nederlandse aardolie maatschappij': 'NAM',
    'nederlandse badmintonbond': 'NBB',
    'nederlandse basketbalbond': 'NBB',
    'nederlandse beugelbond': 'NBB',
    'nederlandse boekverkopersbond': 'NBb',
    'nederlandse boksbond': 'NBB',
    'nederlandse bridgebond': 'NBB',
    'nederlandse christelijke radio-vereniging': 'NCRV',
    'nederlandse christelijke werkgeversorganisatie': 'NCW',
    'nederlandse gebarentaal': 'NGT',
    'nederlandse jeugdherbergcentrale': 'NJHC',
    'nederlandse mededingingsautoriteit': 'NMa',
    'nederlandse officierenvereniging': 'NOV',
    'nederlandse omroepstichting': 'NOS',
    'nederlandse onderzoekschool vrouwenstudies': 'NOV',
    'nederlandse organisatie voor internationale bijstand': 'NOVIB',
    'nederlandse organisatie voor toegepast-natuurwetenschappelijk onderzoek': 'TNO',
    'nederlandse organisatie voor wetenschappelijk onderzoek': 'NWO',
    'nederlandse organisatie vrijwilligers': 'NOV',
    'nederlandse programmastichting': 'NPS',
    'nederlandse racquetball associatie': 'NRA',
    'nederlandse spoorwegen': 'NS',
    'nederlandse vereniging van antroposofische zorgaanbieders': 'NVAZ',
    'nederlandse vereniging van artsen in de zwakzinnigenzorg': 'NVAZ',
    'nederlandse vereniging van dansleraren': 'NVD',
    'nederlandse vereniging van dierentuinen': 'NVD',
    'nederlandse vereniging van diëtisten': 'NVD',
    'nederlandse vereniging van journalisten': 'NVJ',
    'nederlandse vereniging van ziekenhuisapothekers': 'NVZA',
    'nederlandse vereniging voor seksuele hervorming': 'NVSH',
    'nederlandse voedsel- en warenautoriteit': 'NVWA',
    'nederlandse volleybalbond': 'Nevobo',
    'nederlandse zorgautoriteit': 'NZa',
    'neonatale intensive care unit': 'nicu',
    'netherlands universities foundation for international cooperation': 'Nuffic',
    'network termination type 1': 'NT1',
    'neus-, keel- en oorheelkun­de': 'nko',
    'neutrino': 'ino',
    'neutronenbom': 'N-bom',
    'niet van toepassing': 'n.v.t.',
    'non-gouvernementele organisatie': 'ngo',
    'niet-rokend': 'n.r.',
    'nieuw sociaal contract': 'NSC',
    'nieuw-vlaamse alliantie': 'N-VA',
    'nieuwe testament': 'N.T.',
    'nip-test': 'NIPT',
    'nomen nescio': 'N.N.',
    'nominatief': 'nom.',
    'nominativus': 'nom.',
    'non-fungible token': 'NFT',
    'non-playable character': 'NPC',
    'noodmaatregel overbrugging voor werkbehoud': 'NOW',
    'noord- en zuid-hollandsche redding-maatschappij': 'NZHRM',
    'noord-atlantische verdragsorganisatie': 'NAVO',
    'noorderbreedte': 'N.Br.',
    'normaal amsterdams peil': 'NAP',
    'north atlantic treaty organisation': 'NATO',
    'nota bene': 'NB',
    'november': 'nov.',
    'nuclear security summit': 'NSS',
    'numero': 'no.',
    'nummer': 'nr.',
    'obesitas-hypoventilatiesyndroom': 'OHS',
    'obsessive-compulsive disorder': 'OCD',
    'obstructieve slaapapneu': 'OSA',
    'obstructieveslaapapneusyndroom': 'OSAS',
    'of iets dergelijks': 'o.i.d.',
    'oh my god': 'OMG',
    'oktober': 'okt.',
    'oké': 'OK',
    'olympisch kwalificatietoernooi': 'OKT',
    'olympische spelen': 'OS',
    'omgeving': 'omg.',
    'omzetbelasting': 'ob',
    'onbekend': 'onb.',
    'onder andere': 'o.a.',
    'onder anderen': 'o.a.',
    'onder gebruikelijk voorbehoud': 'o.g.v.',
    'onder leiding van': 'o.l.v.',
    'onder meer': 'o.m.',
    'onder vermelding van': 'o.v.v.',
    'ondernemingsraad': 'or',
    'onderwijsmanagementteam': 'OMT',
    'onderzoek en ontwikkeling': 'O&O',
    'onderzoeker in opleiding': 'oio',
    'one more thing': 'OMT',
    'ongebonden': 'ongeb.',
    'ongeveer': 'ong.',
    'ongewenst kinderloos': 'ok',
    'onovergankelijk': 'onoverg.',
    'onroerendezaakbelasting': 'ozb',
    'ons soort mensen': 'osm',
    'ontwikkelingssamenwerking': 'OS',
    'onvoldoende': 'o',
    'onvoltooid tegenwoordige tijd': 'o.t.t.',
    'onvoltooid tegenwoordige toekomende tijd': 'o.t.t.t.',
    'onvoltooid verleden tijd': 'o.v.t.',
    'onvoltooid verleden toekomende tijd': 'o.v.t.t.',
    'onze-lieve-vrouw': 'O.L.V.',
    'onzes inziens': 'o.i.',
    'oosterlengte': 'OL',
    'op basis van': 'o.b.v.',
    'op erewoord retour': 'o.e.r.',
    'op grond van': 'o.g.v.',
    'open source': 'OS',
    'open vlaam­se li­be­ra­len en de­mo­cra­ten': 'Open Vld',
    'openbaar centrum voor maatschappelijk welzijn': 'OCMW',
    'openbaar lichaam bonaire': 'OLB',
    'openbaar lichaam saba': 'OLS',
    'openbaar ministerie': 'OM',
    'openbaar vervoer': 'ov',
    'openbare basisschool': 'obs',
    'operatiekamer': 'ok',
    'operatiekwartier': 'ok',
    'operating system': 'OS',
    'opere citato': 'op. cit.',
    'opmerking': 'opm.',
    'oppervlakte': 'opp.',
    'organic light-emitting diode': 'oled',
    'organisatie van afrikaanse eenheid': 'OAE',
    'organisatie voor economische samenwerking en ontwikkeling': 'OEES',
    'organisatie voor veiligheid en samenwerking in europa': 'OVSE',
    'organization of the petroleum exporting countries': 'OPEC',
    'orthopedische manuele therapie': 'OMT',
    'oude testament': 'O.T.',
    'outbreak management team': 'OMT',
    'outright monetary transactions': 'OMT',
    'overdrachtelijk': 'overdr.',
    'overgankelijk': 'overg.',
    'overweg met een automatische knipperinstallatie': 'aki',
    'paardenkracht': 'pk',
    'pacifistisch-socialistische partij': 'PSP',
    'pagina': 'pag.',
    'palestinian liberation organization': 'PLO',
    'paragraaf': 'par.',
    'paramethoxyamfetamine': 'PMA',
    'park-and-ride': 'P+R',
    'parti social chrétien': 'PSC',
    'parti socialiste': 'PS',
    'partij van de arbeid (belgië)': 'PVDA',
    'partij van de arbeid': 'PvdA',
    'partij voor de dieren': 'PvdD',
    'partij voor de vrijheid': 'PVV',
    'partij voor vrijheid en vooruitgang': 'PVV',
    'partnerruil': 'pr',
    'parts per million': 'ppm',
    'passief': 'pass.',
    'password authentication protocol': 'PAP',
    'pedagogische academie': 'p.a.',
    'pedagogische academie voor het basisonderwijs': 'pabo',
    'pedriatic condition falsification': 'PCF',
    'peer-to-peer': 'p2p',
    'pelotonscommandant': 'pc',
    'penitentiair inrichtingswerker': 'piw',
    'per': 'p.',
    'per adres': 'p.a.',
    'per persoon': 'p.p.',
    'per persoon per nacht': 'p.p.p.n.',
    'perfluoroctaansulfonzuur': 'PFOS',
    'perfluoroctaanzuur': 'PFOA',
    'personal computer': 'pc',
    'personal digital assistent': 'pda',
    'personeel en organisatie': 'P&O',
    'personeelszaken': 'PZ',
    'personenvennootschap met beperkte aansprakelijkheid': 'pvba',
    'persoon': 'pers.',
    'persoonlijk identificatienummer': 'pin',
    'persoonsgebonden budget': 'pgb',
    'philips sportvereniging': 'PSV',
    'pixels per inch': 'ppi',
    'pizzicato': 'pizz.',
    'plaats delict': 'pd',
    'planbureau voor de leefomgeving': 'PBL',
    'plastic verpakkingen, metalen verpakkingen en drinkpakken/drankkartons': 'pmd',
    'plusminus': 'plm.',
    'politiek correct': 'pc',
    'politiek correcte)': 'poco',
    'politieke partij radikalen': 'PPR',
    'politiezone': 'PZ',
    'poly- en perfluoralkylstoffen': 'PFAS',
    'polychloorbifenyl': 'pcb',
    'polycyclische aromatische koolwaterstof': 'pak',
    'polyethyleentereftalaat': 'pet',
    'polytetrafluorethyleen': 'PTFE',
    'polyvinylchloride': 'pvc',
    'pools persbureau': 'PAP',
    'portable document format': 'pdf',
    'positionele obstructieve slaapapneu': 'POSA',
    'post meridiem': 'p.m.',
    'post telefoon telegraaf': 'PTT',
    'post-acute sequelae of covid-19': 'PASC',
    'poste restante': 'p.r.',
    'postexertionele malaise': 'PEM',
    'postintensivecaresyndroom': 'PICS',
    'postpostscriptum': 'PPS',
    'postrekening': 'prk',
    'postrekeningnummer': 'prk',
    'postscriptum': 'PS',
    'posttraumatische stressstoornis': 'PTSS',
    'potentiaal hydrogenium': 'pH',
    'praktisch basisgerichte leerweg': 'pbl',
    'praktisch kadergerichte leerweg': 'pkl',
    'premiepensioeninstelling': 'PPI',
    'prepositie': 'prep.',
    'preventie-unit binnenstad': 'PUB',
    'primaire sclerosende cholangitis': 'PSC',
    'pro memorie': 'p.m.',
    'procent': 'pct.',
    'proces-verbaal': 'pv',
    'procesbeschikbaarheidslocatie': 'pbl',
    'procureur-generaal': 'pg',
    'professionele bacheloropleiding': 'pba',
    'professor': 'prof.',
    'programma aanpak stikstof': 'PAS',
    'provinciaal': 'prov.',
    'provinciale waterstaat': 'PW',
    'provincie': 'prov.',
    'public relations': 'pr',
    'publiek-private samenwerking': 'pps',
    'publieke werken': 'PW',
    'puur plantaardige olie': 'ppo',
    'qualitate qua': 'q.q.',
    'quality-adjusted life year': 'qaly',
    'queens park rangers': 'QPR',
    'queteletindex': 'QI',
    'quod erat demonstrandum': 'q.e.d.',
    'raad van advies': 'rva',
    'raad van advies (bestuursorgaan antillen)': 'RvA',
    'raad van bestuur': 'rvb',
    'raad van commissarissen': 'rvc',
    'raad van state': 'RvS',
    'raad van toezicht': 'rvt',
    'raad voor cultuur': 'RvC',
    'radiation absorbed dose': 'rad',
    'radio télévision luxembourg': 'RTL',
    'radio volksuniversiteit': 'RVU',
    'radio-télévision belge de la communauté française': 'RTBF',
    'random access memory': 'RAM',
    'rapid eye movement': 'rem',
    'read-only memory': 'ROM',
    'recherchesamenwerkingsteam': 'RST',
    'rechterlijk ambtenaar in opleiding': 'raio',
    'rechtspersonen- en samenwerkingsverbandeninformatienummer': 'rsin',
    'recto': 'r.',
    'redacteur': 'red.',
    'redactie': 'red.',
    'referaat': 'ref.',
    'referentie': 'ref.',
    'reformatorische politieke federatie': 'RPF',
    'regel': 'r.',
    'regeling tijdelijke arbeidsplaatsen': 'TAP',
    'regeling voor vervroegde uittreding': 'RVU',
    'regie van telegrafie en telefonie': 'RTT',
    'regionaal opleidings- of opleidingencentrum': 'roc',
    'regionale instelling voor de ambulante geestelijke gezondheidszorg': 'Riagg',
    'regionale verwijzingscommissie': 'rvc',
    'relatie': 'rel.',
    'relief of missing out': 'romo',
    'repetitive strain injury': 'RSI',
    'research and development': 'R&D',
    'respectievelijk': 'resp.',
    'respiratoir syncytieel virus': 'RSV',
    'return on sales': 'ROS',
    'rhythm-and-blues': 'arrenbie',
    'ribonucleic acid': 'RNA',
    'rigid hull inflatable boat': 'rhib',
    'rijksdienst caribisch nederland': 'RCN',
    'rijksdienst voor arbeidsvoorziening': 'RVA',
    'rijksdienst voor maatschappelijke zekerheid': 'RMZ',
    'rijksgroepsregeling werkloze werknemers': 'RWW',
    'rijksinstituut voor natuurbeheer': 'RIN',
    'rijksinstituut voor oorlogsdocumentatie': 'RIOD',
    'rijksinstituut voor visserijonderzoek': 'RIVO',
    'rijksinstituut voor volksgezondheid en milieu': 'RIVM',
    'rijksinstituut voor ziekte- en invaliditeitsverzekering': 'RIZIV',
    'rijksministerraad': 'RMR',
    'rijksvoorlichtingsdienst': 'RVD',
    'rijkswaterstaat': 'RWS',
    'roestvrij staal': 'rvs',
    'roestvrijstalen': 'rvs',
    'rooms-katholiek': 'r.-k.',
    'rooms-katholieke combinatie': 'RKC',
    'rote armee fraktion': 'RAF',
    'royal air force': 'RAF',
    'rural professional': 'rup',
    'rust- en verzorgingstehuis': 'rvt',
    'répondez s\'il vous plaît': 'r.s.v.p.',
    'réponse s\'il vous plaît': 'r.s.v.p.',
    'röntgenequivalent mens': 'rem',
    's\'il vous plaît': 's.v.p.',
    'sadomasochisme': 'sm',
    'save our souls': 'SOS',
    'school voor hoger algemeen voortgezet onderwijs': 'havo',
    'school voor hoger beroepsonderwijs': 'hbo',
    'school voor hoger economisch en administratief onderwijs': 'heao',
    'school voor lager economisch en administratief onderwijs': 'leao',
    'school voor lager huishoud- en nijverheidsonderwijs': 'lhno',
    'school voor middelbaar algemeen voortgezet onderwijs': 'mavo',
    'school voor middelbaar beroepsonderwijs': 'mbo',
    'school voor middelbaar economisch en administratief onderwijs': 'meao',
    'school voor uitgebreid lager onderwijs': 'ulo',
    'school voor volwassenenonderwijs': 'vavo',
    'school voor voorbereidend middelbaar beroepsonderwijs': 'vmbo',
    'school voor voorbereidend wetenschappelijk onderwijs': 'vwo',
    'schoolexamen': 'SE',
    'schriftelijke overhoring': 'so',
    'schutzstaffel': 'SS',
    'science, technology, engineering, mathematics': 'STEM',
    'sciencefiction': 'sf',
    'search engine optimization': 'SEO',
    'secetariaat': 'secr.',
    'second edition': 'SE',
    'second generation': '2G',
    'seconde': 'sec.',
    'secretaris': 'secr.',
    'secundair beroepsonderwijs': 'sbo',
    'seksueel overdraagbare aandoening': 'soa',
    'semester': 'sem.',
    'senior': 'sr.',
    'sensu lato': 's.l.',
    'september': 'sep',
    'severe acute respiratory syndrome': 'SARS',
    'short message service': 'sms',
    'sine loco': 's.l.',
    'sine loco et anno': 's.l.e.a.',
    'sine nomine': 's.n.',
    'slank': 'sl.',
    'small': 'S',
    'small modular reactor': 'SMR',
    'sociaal-economische raad': 'SER',
    'sociaal-economische raad van vlaanderen': 'SERV',
    'sociaalpsychiatrisch verpleegkundige': 'spv',
    'socialistische partij': 'SP',
    'societas europaea': 'SE',
    'society for worldwide interbank financial telecommunication': 'Swift',
    'société anonyme belge d’exploitation de la navigation aérienne': 'Sabena',
    'soortelijk gewicht': 's.g.',
    'soul en calypso': 'soca',
    'special edition': 'SE',
    'special effects': 'SE',
    'special purpose acquisition company': 'spac',
    'spoedeisende hulp': 'SEH',
    'spongiforme encefalopathie': 'SE',
    'spoorwegovergang met automatische halve overwegbomen': 'ahob',
    'sport utility vehicle': 'SUV',
    'sportclub': 'SC',
    'staatkundig gereformeerde partij': 'SGP',
    'staats sicherheitsdienst': 'Stasi',
    'staatsblad': 'Stbl.',
    'standard generalized markup language': 'SGML',
    'steun en consultatie bij euthanasie in nederland': 'SCEN',
    'stichting collectieve propaganda nederlandse boek': 'CPNB',
    'stichting etherreclame': 'Ster',
    'stichting ideële reclame': 'SIRE',
    'stichting moslimomroep nederland': 'SMON',
    'stichting tot exploitatie van mechanische reproductierechten der auteurs': 'Stemra',
    'stilo novo': 'st.n.',
    'stilo veteri': 's.v.',
    'strategic arms limitation talks': 'SALT',
    'structureel echoscopisch onderzoek': 'seo',
    'sub verbo': 's.v.',
    'sub voce': 's.v.',
    'subcutane implanteerbare cardioverter-defibrillator': 's-icd',
    'substantief': 'subst.',
    'substantivum': 'subst.',
    'super audio compact disc': 'sacd',
    'supergiant': 'super-G',
    'supersnelle trein': 'sst',
    'surinaamse dollar': 'SRD',
    'sustainable aviation fuel': 'SAF',
    'systeem': 'DigiD',
    'système international d\'unités': 'SI',
    'ter aangehaalde plaatse': 't.a.p.',
    'te gebruiken tot': 't.g.t.',
    'te gelegener tijd': 't.g.t.',
    'te huur': 't.h.',
    'te huur aangeboden': 't.h.a.',
    'te koop': 't.k.',
    'te koop aangeboden': 't.k.a.',
    'te weten': 't.w.',
    'te zijner tijd': 't.z.t.',
    'technisch geleid vertrek': 'TGV',
    'technisch secundair onderwijs': 'tso',
    'technische hogeschool': 'th',
    'technische hogeschool twente': 'THT',
    'technische universiteit': 'TU',
    'tegemoetkoming vaste lasten': 'TVL',
    'tegemoetkoming woonlasten kamerhuurders': 'twk',
    'tegen elk aannemelijk bod': 't.e.a.b.',
    'tegenover': 'tgov.',
    'telefoon': 'tel.',
    'telefoonnummer': 'telnr.',
    'telegrafnoje agentstvo sovjetskogo sojoeza': 'Tass',
    'telegram': 'tel.',
    'televisie': 'tv',
    'televisie academie': 'Teleac',
    'televisie- en radio-omroepstichting': 'TROS',
    'telwoord': 'telw.',
    'ten aanzien van': 't.a.v.',
    'ten bate van': 't.b.v.',
    'ten behoeve van': 't.b.v.',
    'ten gevolge van': 't.g.v.',
    'ten gunste van': 't.g.v.',
    'ten honderd': 't.h.',
    'ten laste van': 't.l.v.',
    'ten minste houdbaar tot': 't.h.t.',
    'ten name van': 't.n.v.',
    'ten opzichte van': 't.o.v.',
    'ten overstaan van': 't.o.v.',
    'ten tijde van': 't.t.v.',
    'ter attentie van': 't.a.v.',
    'ter gelegenheid van': 't.g.v.',
    'ter hoogte van': 't.h.v.',
    'ter waarde van': 't.w.v.',
    'terbeschikkingstelling': 'tbs',
    'terugwerkende kracht': 'twk',
    'tetrahydrocannabinol': 'THC',
    'tewerkgestelde werkloze': 'tww',
    'tewerkstellingsvergunning': 'twv',
    'the european fine art fair': 'TEFAF',
    'theoretisch kadergerichte leerweg': 'tkl',
    'third generation': '3G',
    'thé dansant': 't.d.',
    'tijdelijke ondersteuning noodzakelijke kosten': 'TONK',
    'tijdelijke overbruggingsregeling voor flexibele arbeidskrachten': 'TOFA',
    'tijdelijke overbruggingsregeling zelfstandig ondernemers': 'Tozo',
    'timemanagement': 'TM',
    'toegepaste economische wetenschappen': 'tew',
    'toekomend': 'toek.',
    'toroidalnaja kamera': 'tokamak',
    'tot en met': 't.e.m.',
    'tourist trophy': 'TT',
    'tout à toi': 't.à.t.',
    'trafficmanagement': 'TM',
    'train à grande vitesse': 'tgv',
    'trans-europa-expres': 'TEE',
    'trans-exclusionary radical feminist': 'terf',
    'transcendente meditatie': 'tm',
    'transcient ischemic attack': 'TIA',
    'transititef': 'tr.',
    'transmissible spongiform encephalopathy': 'TSE',
    'transnationale universiteit limburg': 'tUL',
    'trefwoord': 'trefw.',
    'trifluorazijnzuur': 'TFA',
    'trinitrotolueen': 'TNT',
    'triple a': 'AAA',
    'tube luminescent': 'tl',
    'tuberculose': 'tb',
    'tussenschoolse opvang': 'tso',
    'tussenwerpsel': 'tussenw.',
    'tussenwoning': 'tussenw.',
    'televisie': 'teevee',
    'twee dimensies': '2D',
    'tweede kamer': 'T.K.',
    'tweede wereldoorlog': 'WO II',
    'tweedimensionaal': '2D',
    'twitterjockey': 'tj',
    'uitgave': 'uitg.',
    'uitgestelde vergoeding': 'UV',
    'uitgever': 'uitg.',
    'uitgeverij': 'uitg.',
    'uitkering in het kader van de wao': 'WAO',
    'uitkering in kader van de algemene ouderdomswet': 'AOW',
    'uitkering via de noodmaatregel overbrugging voor werkbehoud': 'NOW',
    'uitkering via de tegemoetkoming vaste lasten': 'TVL',
    'uitkering via de tijdelijke ondersteuning noodzakelijke kosten': 'TONK',
    'uitkering via de tijdelijke overbruggingsregeling voor flexibele arbeidskrachten': 'TOFA',
    'uitkering via de tijdelijke overbruggingsregeling zelfstandig ondernemers': 'Tozo',
    'uitvoeringsinstantie': 'uvi',
    'ulster unionist party': 'UUP',
    'ultra high frequency': 'UHF',
    'ultra low frequency': 'ULF',
    'ultrahigh-definition': 'uhd',
    'ultrahigh-definition televisie': 'uhdtv',
    'ultrahoog rendement': 'uhr',
    'ultralightvliegtuig': 'ulv',
    'ultraviolet': 'uv',
    'unidentified aerial phenomenon': 'UAP',
    'unidentified floating object': 'ufo',
    'unidentified flying object': 'ufo',
    'unie van socialistische sovjetrepublieken': 'USSR',
    'unie van zelfstandige ondernemers': 'UNIZO',
    'uniform resource locator': 'URL',
    'union cycliste internationale': 'UCI',
    'unique sellingpoint': 'USP',
    'united kingdom': 'UK',
    'united nations': 'UN',
    'united nations conference on trade and development': 'UNCTAD',
    'united nations educational, scientific and cultural organization': 'UNESCO',
    'united nations interim force in lebanon': 'UNIFIL',
    'united nations international children’s emergency fund': 'UNICEF',
    'united nations organization': 'UNO',
    'united nations relief and works agency for palestine refugees': 'UNRWA',
    'united states': 'US',
    'united states anti-doping agency': 'USADA',
    'united states of america': 'USA',
    'universal mobile telecommunications system': 'UMTS',
    'universal serial bus': 'USB',
    'universal serial bus a': 'USB-A',
    'universal serial bus c': 'USB-C',
    'universitair docent': 'ud',
    'universitair hoofddocent': 'uhd',
    'universitair ziekenhuis': 'uz',
    'universiteit utrecht': 'UU',
    'universiteit van amsterdam': 'UvA',
    'universiteitsbibliotheek': 'ub',
    'unrepresented nations and peoples organization': 'UNPO',
    'utrechts nieuwsblad': 'UN',
    'vakbond voetbal oefenmeesters nederland': 'VVON',
    'van de': 'v.d.',
    'van dit': 'v.d.',
    'van een': 'v.e.',
    'van het': 'v.h.',
    'van links naar rechts': 'v.l.n.r.',
    'van rechts naar links': 'v.r.n.l.',
    'van tijd tot tijd': 'v.t.t.t.',
    'vanaf': 'v.a.',
    'vehicle identification number': 'vin',
    'veiligheidsraad': 'VR',
    'veldtoertocht': 'VTT',
    'vennootschap onder firma': 'vof',
    'ventrikelfibrillatie': 'VF',
    'verbond der vlaamse tandartsen': 'VVT',
    'verbond van belgische ondernemingen': 'VBO',
    'verbond van nederlandse ondernemingen': 'VNO',
    'verenigde oost-indische compagnie': 'VOC',
    'vereeniging van arbeiders radio amateurs': 'VARA',
    'verenigde arabische emiraten': 'VAE',
    'verenigde naties': 'VN',
    'verenigde staten': 'VS',
    'vereniging van contractspelers': 'VVCS',
    'vereniging van dienstplichtige militairen': 'VVDM',
    'vereniging van eigenaren': 'vve',
    'vereniging van mede-eigenaars': 'vme',
    'vereniging van nederlandse gemeenten': 'VNG',
    'vereniging van onderzoeksjournalisten': 'VVOJ',
    'vereniging van samenwerkende nederlandse universiteiten': 'VSNU',
    'vereniging van tafeltennistrainers': 'VVTT',
    'vereniging vastgoedjuristen': 'VVJ',
    'vereniging voor vlaamse jeugddiensten': 'VVJ',
    'vereniging voor vreemdelingenverkeer': 'VVV',
    'vereniging zonder winstoogmerk': 'vzw',
    'vergelijk': 'vgl.',
    'verklaring omtrent het gedrag': 'vog',
    'verliest van': 'v.v.',
    'veronica omroeporganisatie': 'VOO',
    'verpleging, verzorging, thuiszorg': 'VVT',
    'vers': 'vs.',
    'verso': 'v.',
    'versus': 'vs.',
    'vertaler': 'vert.',
    'vertaling': 'vert.',
    'vervroegde invrijheidstelling': 'vi',
    'vervroegde uittreding uit dienstverband': 'VUT',
    'vervuilingseenheid': 've',
    'verwacht': 'verw.',
    'very important person': 'vip',
    'very light jet': 'vlj',
    'vice versa': 'v.v.',
    'vicepresident': 'vp',
    'video assistant referee': 'VAR',
    'video graphics array': 'VGA',
    'video random-access memory': 'VRAM',
    'videocassetterecorder': 'VCR',
    'videojockey': 'vj',
    'vier dimensies': '4D',
    'vierdimensionaal': '4D',
    'vierentwintig op vierentwintig': '24/24',
    'vierentwintig zeven': '24/7',
    'virtual reality': 'VR',
    'vitamine': 'vit.',
    'vj': 'veejay',
    'vlaams aktiekomitee tegen atoomwapens': 'VAKA',
    'vlaams belang': 'VB',
    'vlaams economisch verbond': 'VEV',
    'vlaamse automobilistenbond': 'VAB',
    'vlaamse dienst voor arbeidsbemiddeling en beroepsopleiding': 'VDAB',
    'vlaamse gebarentaal': 'VGT',
    'vlaamse jeugdherbergcentrale': 'VJHC',
    'vlaamse journalistenvereniging': 'VJV',
    'vlaamse juristenvereniging': 'VJV',
    'vlaamse liberalen en democraten - partij van de burger': 'VLD',
    'vlaamse radio- en televisieomroeporganisatie': 'VRT',
    'vlaamse toeristenbond': 'VTB',
    'vlaamse toeristenbond - vlaamse automobilistenbond': 'VTB-VAB',
    'vlaamse vereniging van beroepsjournalisten': 'VVJ',
    'vlaamse volksbeweging': 'VVB',
    'vlaamse volleybalbond': 'VVB',
    'vliegtuig van a.v. roe and company': 'Avro',
    'vocatief': 'voc.',
    'vocativus': 'voc.',
    'voegwoord': 'voegw.',
    'voegwoordelijk': 'voegw.',
    'voetbalclub paris saint-germain': 'PSG',
    'voetbalvereniging': 'vv',
    'voetgangersoversteekplaats': 'vop',
    'voldoende': 'v',
    'voldoende onderricht persoon': 'vop',
    'volgend': 'vlg.',
    'volgens': 'vlg.',
    'volgnummer': 'volgnr.',
    'volkspartij voor vrijheid en democratie': 'VVD',
    'volkspolizei': 'Vopo',
    'volksunie': 'VU',
    'volksuniversiteit': 'vu',
    'voltooid tegenwoordige tijd': 'v.t.t.',
    'voltooid tegenwoordige toekomende tijd': 'v.t.t.t.',
    'voltooid verleden tijd': 'v.v.t.',
    'voltooid verleden toekomende tijd': 'v.v.t.t.',
    'voor': 'vr',
    'voor christus': 'v.Chr.',
    'voor wat betreft': 'v.w.b.',
    'voorbereidend beroepsonderwijs': 'vbo',
    'voorbereidend middelbaar beroepsonderwijs': 'vmbo',
    'voorbereidend secundair beroepsonderwijs': 'vsbo',
    'voorbereidend wetenschappelijk onderwijs': 'vwo',
    'voorheen': 'vh.',
    'voorlopige toelating tot tewerkstelling': 'VTT',
    'voormiddag': 'vm.',
    'voornaamwoord': 'vnw.',
    'voornaamwoordelijk': 'vnw.',
    'voornamelijk': 'vrnl.',
    'voortgezet algemeen volwassenenonderwijs': 'vavo',
    'voortgezet onderwijs': 'vo',
    'voortgezet onderwijs op juniorenniveau': 'voj',
    'voortgezet onderwijs op seniorenniveau': 'vos',
    'voortgezet speciaal onderwijs': 'vso',
    'voorwaardelijke invrijheidstelling': 'vi',
    'voorwaardelijke vergunning tot verblijf': 'vvtv',
    'voorzetsel': 'voorz.',
    'voorzitter': 'voorz.',
    'vrij langs boord': 'v.l.b.',
    'vrij nederland': 'VN',
    'vrij op naam': 'v.o.n.',
    'vrij syndicaat van het openbaar ambt': 'VSOA',
    'vrijdag': 'vr.',
    'vrije indische partij': 'VIP',
    'vrije universiteit': 'VU',
    'vrije universiteit brussel': 'VUB',
    'vrijstaand': 'vrijst.',
    'vrijzinnig protestantse radio omroep': 'VPRO',
    'vrouw': 'vr.',
    'vrouwelijk': 'vrl.',
    'vulvaire intra-epitheliale neoplasie': 'VIN',
    'vzw belgisch warmbloedpaard': 'BWP',
    'waardering onroerende zaken': 'WOZ',
    'waarnemend': 'wnd.',
    'waaronder': 'w.o.',
    'waarschijnlijk': 'wsch.',
    'warmte-krachtkoppeling': 'wkk',
    'warren abstract machine': 'WAM',
    'wat betreft': 'w.b.',
    'wat verder ter tafel komt': 'w.v.t.t.k.',
    'watercloset': 'wc',
    'weduwe': 'wed.',
    'weduwe van': 'w.v.',
    'weduwnaar': 'wedn.',
    'weduwnaar van': 'w.v.',
    'wegenverkeerswet': 'WVW',
    'weledele': 'Weled.',
    'wereldkampioenschap': 'WK',
    'wereldoorlog': 'WO',
    'werkgeversvereniging openbare bibliotheken': 'Wob',
    'werkhervatting gedeeltelijk arbeidsgeschikten': 'WGA',
    'werkloosheidswet': 'WW',
    'werktijdverkorting': 'wv',
    'werkwoord': 'werkw.',
    'werkwoordelijk': 'ww.',
    'westerlengte': 'WL',
    'wet aanpassingsmechanismen': 'WAM',
    'wet aansprakelijkheidsverzekering motorrijtuigen': 'WAM',
    'wet administratieve lastenverlichting en vereenvoudiging in de sociale verzekeringen': 'Walvis',
    'wet administratieve rechtspraak overheidsbeschikkingen': 'AROB',
    'wet algemene bepalingen omgevingsrecht': 'Wabo',
    'wet arbeidsongeschiktheidsvoorziening jonggehandicapten': 'Wajong',
    'wet koppeling met afwijkingsmogelijkheid': 'WKA',
    'wet op de arbeidsongeschiktheidsverzekering': 'WAO',
    'wet op de ketenaansprakelijkheid': 'WKA',
    'wet op de sociale werkvoorziening': 'WSW',
    'wet op het voortgezet onderwijs': 'WVO',
    'wet open overheid': 'Woo',
    'wet openbaarheid van bestuur': 'Wob',
    'wet schuldsanering natuurlijke personen': 'WSNP',
    'wet toelating zorginstellingen': 'WTZ',
    'wet werk en inkomen naar arbeidsvermogen': 'WIA',
    'wetboek': 'Wetb.',
    'wetboek van strafrecht': 'W.v.Str.',
    'wetenschappelijk onderwijs': 'wo',
    'wettelijke aansprakelijkheid': 'WA',
    'what the fuck': 'wtf',
    'what you see is what you get': 'wysiwyg',
    'white anglo-saxon protestant': 'WASP',
    'wielerbond vlaanderen': 'WBV',
    'windows media audio': 'wma',
    'wint na strafschoppen': 'w.n.s.',
    'wint op punten': 'w.o.p.',
    'wint van': 'w.v.',
    'wireless application protocol': 'WAP',
    'wireless local area network': 'WLAN',
    'wives and girlfriends': 'WAG',
    'woensdag': 'woe',
    'woningbouwvereniging': 'wbv',
    'woon-zorgcentrum': 'wzc',
    'woon-zorgcomplex': 'wozoco',
    'woonzorgcentrum': 'wzc',
    'woonzorgcomplex': 'wozoco',
    'world anti-doping agency': 'WADA',
    'world health organization': 'WHO',
    'world kickboxing association': 'WKA',
    'world wide web': 'www',
    'ww-uitkering': 'WW',
    'you only live once': 'yolo',
    'young urban creative': 'yuc',
    'young urban professional': 'yup',
    'zaliger gedachtenis': 'z.g.',
    'zaterdag': 'zat',
    'zeer goed': 'zg',
    'zeer goed onderhouden': 'z.g.o.h.',
    'zeer kort verhaal': 'zkv',
    'zeer moeilijk lerende kinderen': 'zmlk',
    'zeer moeilijk opvoedbare kinderen': 'zmok',
    'zeer open asfalt': 'zoa',
    'zeer open asfaltbeton': 'zoab',
    'zeer zorgwekkende stof': 'ZZS',
    'zelfstandig': 'zelfst.',
    'zelfstandig academisch personeel': 'ZAP',
    'zelfstandig behandelcentrum': 'zbc',
    'zelfstandig bestuursorgaan': 'zbo',
    'zelfstandig naamwoord': 'znw.',
    'zeven op zeven': '7/7',
    'zeven tegen zeven': '7x7',
    'zie ommezijde': 'z.o.z.',
    'ziekteverzuimpercentage': 'zvp',
    'zijne heiligheid': 'Z.H.',
    'zijne hoogheid': 'Z.H.',
    'zijne koninklijke hoogheid': 'Z.K.H.',
    'zijne koninklijke majesteit': 'Z.K.M.',
    'zijns inziens': 'z.i.',
    'zo goed als nieuw': 'z.g.a.n.',
    'zo spoedig mogelijk': 'z.s.m.',
    'zoekt': 'zkt.',
    'zoekt kennismaking met': 'z.k.m.',
    'zogenaamd': 'zg.',
    'zondag': 'zo',
    'zonder bericht van verhindering': 'z.b.v.v.',
    'zonder jaar': 'z.j.',
    'zonder pension': 'z.p.',
    'zonder plaats': 'z.pl.',
    'zonder uitgever': 'z.u.',
    'zorgzwaartepakket': 'zzp',
    'zuiderbreedte': 'ZB',
    'československá socialistická re­pu­bli­ka': 'ČSSR',
}
